export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS"
export const CALL_SIGN_UP_API = "CALL_SIGN_UP_API"
export const CALL_LOGIN_API = "CALL_LOGIN_API"
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS"
